name: 'seed-plugins'
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  seedPlugins:
    runs-on: ubuntu-latest
    steps:
      - name: Seed plugins 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://dotfyle.com/api/seeder/plugins
          configuration: '{ "method": "GET", "headers": {"Authorization": "${{ secrets.INTERNAL_API_TOKEN }}"} }'
          retry: true
