name: 'sync-configs'
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  syncConfigs:
    runs-on: ubuntu-latest
    steps:
      - name: Sync configs 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://dotfyle.com/api/sync/configs
          configuration: '{ "method": "GET", "headers": {"Authorization": "${{ secrets.INTERNAL_API_TOKEN }}"} }'
          retry: true
